services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: student-portal-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - student-portal-network
    depends_on:
      - mysql
      - redis

  nginx:
    image: nginx:alpine
    container_name: student-portal-nginx
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8000}:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - student-portal-network
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: student-portal-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-student_portal}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_USER: ${DB_USERNAME:-laravel}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "${DB_PORT:-3306}:3306"
    networks:
      - student-portal-network
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:7-alpine
    container_name: student-portal-redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis-data:/data
    networks:
      - student-portal-network
    command: redis-server --appendonly yes

networks:
  student-portal-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
  redis-data:
    driver: local
